Add auth pages.
yevhenprudnik/heap-client pull request #4
Opened 2023-04-20 20:09 UTC by Xameon

Login and register pages were added.

2023-04-20 20:38 UTC, GLFV requested changes

2023-04-20 20:38 UTC, GLFV commented on src/components/Login/Login.css
> +    width: 20rem;
use vw or vh instead rem

2023-05-02 12:19 UTC, yevhenprudnik requested changes

2023-05-02 12:19 UTC, yevhenprudnik commented on src/App.js
> +  const [user, setUser] = useState({});
Use null instead of {}.

2023-05-02 12:19 UTC, yevhenprudnik commented on src/App.js
> +    (async () => {
Use usual function instead of ifi.

2023-05-02 12:19 UTC, yevhenprudnik commented on src/App.js
> +    (async () => {
Optional.

2023-05-02 12:27 UTC, yevhenprudnik approved these changes

2023-05-02 12:38 UTC, merged